function out = combine_rf_pulses(inputFiles, method, outputDir)
%COMBINE_RF_PULSES Combine unencoded pulses into encoded pulses.
%   Fourier: number of encoded pulses equals number of input pulses.
%   Hadamard: number of encoded pulses equals the Hadamard matrix order
%   (e.g. 3 inputs -> 4 encoded pulses; 5-8 inputs -> 8 encoded pulses).
%
%   Input pulse phase/amplitude values are first converted into complex
%   waveforms. Encoded pulses are then generated by linear combination in
%   the complex domain and written back as phase/amplitude .RF files.

if nargin < 3 || isempty(outputDir)
    outputDir = pwd;
end

nInput = numel(inputFiles);
if nInput < 1
    error('At least one input pulse file is required.');
end

P = cell(1,nInput);
for k = 1:nInput
    P{k} = speed.read_rf_shape(inputFiles{k});
end

L = numel(P{1}.complex);
for k = 2:nInput
    if numel(P{k}.complex) ~= L
        error('All pulse files must have the same length.');
    end
end

methodLower = lower(char(method));
Xinput = zeros(L,nInput);
for k = 1:nInput
    Xinput(:,k) = P{k}.complex(:);
end

switch methodLower
    case 'fourier'
        nEncoded = nInput;
        E = speed.get_encoding_matrix('fourier', nInput);
        encoded = Xinput * E.';
        Xwork = Xinput;

    case 'hadamard'
        E = speed.get_encoding_matrix('hadamard', nInput);
        nEncoded = size(E,1);

        % Zero-pad missing channels to the full Hadamard order.
        Xwork = zeros(L,nEncoded);
        Xwork(:,1:nInput) = Xinput;

        % Explicit Hadamard combination in the complex domain.
        encoded = zeros(L,nEncoded);
        for row = 1:nEncoded
            z = zeros(L,1);
            for col = 1:nEncoded
                if E(row,col) >= 0
                    z = z + Xwork(:,col);
                else
                    z = z - Xwork(:,col);
                end
            end
            encoded(:,row) = z;
        end

    otherwise
        error('Unsupported method: %s', method);
end

if ~exist(outputDir,'dir')
    mkdir(outputDir);
end

paths = cell(1,nEncoded);
for k = 1:nEncoded
    paths{k} = fullfile(outputDir, sprintf('%s_encoded_%02d.RF', lower(char(method)), k));
    speed.write_rf_shape(paths{k}, encoded(:,k));
end

out.method = method;
out.inputFiles = inputFiles;
out.outputFiles = paths;
out.unencodedMatrix = Xinput;
out.workingMatrix = Xwork;
out.encodedMatrix = encoded;
out.encodingMatrix = E;
out.nInput = nInput;
out.nEncoded = nEncoded;
end
